// Meal Suggestion Service
// Provides weather-based meal recommendations

import { WeatherData } from './weatherService';

export interface MealSuggestion {
  name: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  ingredients: string[];
  benefits: string;
  emoji: string;
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  imageUrl: string;
}

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

const weatherMeals: Record<WeatherData['category'], MealSuggestion[]> = {
  hot: [
    // Breakfast
    {
      name: 'Chilled Greek Yogurt Bowl',
      description: 'Refreshing yogurt with berries and granola',
      calories: 320,
      protein: 18,
      carbs: 42,
      fats: 8,
      ingredients: ['Greek yogurt', 'Mixed berries', 'Honey', 'Granola', 'Chia seeds'],
      benefits: 'High protein, cooling, hydrating, packed with antioxidants',
      emoji: '🥣',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    },
    {
      name: 'Smoothie Bowl',
      description: 'Frozen fruit smoothie with toppings',
      calories: 280,
      protein: 12,
      carbs: 48,
      fats: 6,
      ingredients: ['Frozen banana', 'Berries', 'Almond milk', 'Protein powder', 'Coconut'],
      benefits: 'Cooling, nutrient-dense, easy to digest',
      emoji: '🥤',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    },
    // Lunch
    {
      name: 'Watermelon & Feta Salad',
      description: 'Light refreshing salad with mint',
      calories: 380,
      protein: 12,
      carbs: 28,
      fats: 18,
      ingredients: ['Watermelon', 'Feta cheese', 'Mint', 'Lime', 'Olive oil', 'Arugula'],
      benefits: 'Hydrating, low-calorie, rich in vitamins A & C',
      emoji: '🍉',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1621510456681-2330135e5871?w=800&q=80',
    },
    {
      name: 'Cold Quinoa Salad',
      description: 'Chilled quinoa with vegetables',
      calories: 420,
      protein: 16,
      carbs: 52,
      fats: 16,
      ingredients: ['Quinoa', 'Cucumber', 'Tomatoes', 'Chickpeas', 'Lemon', 'Olive oil'],
      benefits: 'Complete protein, refreshing, fiber-rich',
      emoji: '🥗',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80',
    },
    // Dinner
    {
      name: 'Grilled Fish with Cucumber Salad',
      description: 'Light grilled fish with cooling cucumber',
      calories: 380,
      protein: 38,
      carbs: 18,
      fats: 16,
      ingredients: ['White fish', 'Cucumber', 'Yogurt', 'Dill', 'Lemon'],
      benefits: 'High protein, omega-3, light and cooling',
      emoji: '🐟',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80',
    },
    {
      name: 'Chilled Gazpacho with Chicken',
      description: 'Cold tomato soup with grilled protein',
      calories: 340,
      protein: 32,
      carbs: 24,
      fats: 12,
      ingredients: ['Tomatoes', 'Cucumber', 'Bell peppers', 'Grilled chicken', 'Olive oil'],
      benefits: 'Refreshing, hydrating, high protein',
      emoji: '🍅',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=800&q=80',
    },
    // Snacks
    {
      name: 'Frozen Fruit Popsicles',
      description: 'Homemade fruit ice pops',
      calories: 80,
      protein: 2,
      carbs: 18,
      fats: 1,
      ingredients: ['Mixed berries', 'Coconut water', 'Honey'],
      benefits: 'Hydrating, low-calorie, natural sugars',
      emoji: '🍧',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
    },
    {
      name: 'Cucumber & Hummus',
      description: 'Crisp cucumber with protein-rich hummus',
      calories: 120,
      protein: 6,
      carbs: 14,
      fats: 5,
      ingredients: ['Cucumber', 'Hummus', 'Lemon', 'Paprika'],
      benefits: 'Cooling, hydrating, protein boost',
      emoji: '🥒',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1603046891726-36bfd957e0bf?w=800&q=80',
    },
  ],
  cold: [
    // Breakfast
    {
      name: 'Warm Oatmeal Bowl',
      description: 'Hearty oats with nuts and banana',
      calories: 380,
      protein: 14,
      carbs: 58,
      fats: 12,
      ingredients: ['Steel-cut oats', 'Banana', 'Walnuts', 'Cinnamon', 'Honey'],
      benefits: 'Warming, high fiber, sustained energy',
      emoji: '🥣',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800&q=80',
    },
    {
      name: 'Scrambled Eggs & Avocado Toast',
      description: 'Protein-rich breakfast with healthy fats',
      calories: 420,
      protein: 22,
      carbs: 32,
      fats: 24,
      ingredients: ['Eggs', 'Whole grain bread', 'Avocado', 'Tomatoes', 'Pepper'],
      benefits: 'High protein, warming, keeps you full',
      emoji: '🍳',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80',
    },
    // Lunch
    {
      name: 'Hot Lentil Soup',
      description: 'Warming protein-rich soup',
      calories: 340,
      protein: 18,
      carbs: 52,
      fats: 6,
      ingredients: ['Red lentils', 'Carrots', 'Celery', 'Onions', 'Spices'],
      benefits: 'Warming, high protein, fiber-rich',
      emoji: '🍲',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },
    {
      name: 'Grilled Cheese & Tomato Soup',
      description: 'Comfort food classic',
      calories: 480,
      protein: 20,
      carbs: 54,
      fats: 20,
      ingredients: ['Whole grain bread', 'Cheese', 'Tomatoes', 'Basil', 'Butter'],
      benefits: 'Warming, comforting, satisfying',
      emoji: '🥪',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=800&q=80',
    },
    // Dinner
    {
      name: 'Chicken Stew with Vegetables',
      description: 'Hearty warming stew',
      calories: 420,
      protein: 38,
      carbs: 32,
      fats: 16,
      ingredients: ['Chicken', 'Potatoes', 'Carrots', 'Peas', 'Herbs'],
      benefits: 'High protein, warming, nutrient-dense',
      emoji: '🍛',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1588566565463-180a5b2090d2?w=800&q=80',
    },
    {
      name: 'Baked Salmon with Roasted Veggies',
      description: 'Warm omega-3 rich dinner',
      calories: 460,
      protein: 42,
      carbs: 28,
      fats: 22,
      ingredients: ['Salmon', 'Sweet potato', 'Broccoli', 'Olive oil', 'Garlic'],
      benefits: 'Omega-3, warming, anti-inflammatory',
      emoji: '🐟',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    },
    // Snacks
    {
      name: 'Hot Chocolate with Almonds',
      description: 'Warming cocoa drink with nuts',
      calories: 180,
      protein: 8,
      carbs: 22,
      fats: 8,
      ingredients: ['Cocoa powder', 'Almond milk', 'Honey', 'Almonds'],
      benefits: 'Warming, antioxidants, satisfying',
      emoji: '☕',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800&q=80',
    },
    {
      name: 'Roasted Chickpeas',
      description: 'Crunchy warm protein snack',
      calories: 140,
      protein: 7,
      carbs: 22,
      fats: 3,
      ingredients: ['Chickpeas', 'Olive oil', 'Paprika', 'Cumin'],
      benefits: 'High protein, fiber, warming spices',
      emoji: '🥜',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1587248720327-d4a5f0c2e3d6?w=800&q=80',
    },
  ],
  rainy: [
    // Breakfast
    {
      name: 'Masala Chai & Toast',
      description: 'Spiced tea with protein-rich toast',
      calories: 320,
      protein: 16,
      carbs: 44,
      fats: 10,
      ingredients: ['Masala chai', 'Whole wheat bread', 'Peanut butter', 'Banana'],
      benefits: 'Warming spices boost immunity',
      emoji: '☕',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800&q=80',
    },
    {
      name: 'Vegetable Upma',
      description: 'South Indian savory semolina',
      calories: 280,
      protein: 8,
      carbs: 48,
      fats: 8,
      ingredients: ['Semolina', 'Vegetables', 'Curry leaves', 'Mustard seeds', 'Peanuts'],
      benefits: 'Warm, filling, rich in vegetables',
      emoji: '🍛',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800&q=80',
    },
    // Lunch
    {
      name: 'Hot Noodle Soup',
      description: 'Comforting Asian-style soup',
      calories: 380,
      protein: 22,
      carbs: 52,
      fats: 10,
      ingredients: ['Noodles', 'Chicken', 'Bok choy', 'Ginger', 'Soy sauce'],
      benefits: 'Warming, hydrating, comforting',
      emoji: '🍜',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    },
    {
      name: 'Dal Tadka with Rice',
      description: 'Spiced lentils with steamed rice',
      calories: 420,
      protein: 18,
      carbs: 68,
      fats: 8,
      ingredients: ['Yellow dal', 'Rice', 'Tomatoes', 'Cumin', 'Ghee'],
      benefits: 'Warming, protein-rich, comforting',
      emoji: '🍚',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    },
    // Dinner
    {
      name: 'Butter Chicken with Naan',
      description: 'Creamy tomato-based curry',
      calories: 520,
      protein: 36,
      carbs: 48,
      fats: 22,
      ingredients: ['Chicken', 'Tomatoes', 'Cream', 'Spices', 'Naan bread'],
      benefits: 'Warming, high protein, satisfying',
      emoji: '🍛',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80',
    },
    {
      name: 'Vegetable Biryani',
      description: 'Aromatic spiced rice dish',
      calories: 440,
      protein: 12,
      carbs: 72,
      fats: 12,
      ingredients: ['Basmati rice', 'Mixed vegetables', 'Spices', 'Yogurt', 'Saffron'],
      benefits: 'Warming spices, aromatic, filling',
      emoji: '🍚',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    },
    // Snacks
    {
      name: 'Pakoras (Fritters)',
      description: 'Crispy vegetable fritters',
      calories: 180,
      protein: 6,
      carbs: 24,
      fats: 8,
      ingredients: ['Chickpea flour', 'Onions', 'Spinach', 'Spices'],
      benefits: 'Warm, crispy, perfect for rainy days',
      emoji: '🥟',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    },
    {
      name: 'Ginger Tea with Biscuits',
      description: 'Warming ginger tea',
      calories: 140,
      protein: 3,
      carbs: 26,
      fats: 4,
      ingredients: ['Ginger', 'Tea', 'Honey', 'Whole wheat biscuits'],
      benefits: 'Warming, aids digestion, comforting',
      emoji: '🍪',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80',
    },
  ],
  humid: [
    // Breakfast
    {
      name: 'Fresh Fruit Salad',
      description: 'Mixed seasonal fruits with lime',
      calories: 180,
      protein: 3,
      carbs: 44,
      fats: 1,
      ingredients: ['Papaya', 'Pineapple', 'Grapes', 'Pomegranate', 'Lime'],
      benefits: 'Light, hydrating, enzyme-rich',
      emoji: '🍇',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1564093497595-593b96d80180?w=800&q=80',
    },
    {
      name: 'Green Smoothie',
      description: 'Refreshing vegetable blend',
      calories: 220,
      protein: 8,
      carbs: 38,
      fats: 5,
      ingredients: ['Spinach', 'Cucumber', 'Green apple', 'Ginger', 'Coconut water'],
      benefits: 'Hydrating, detoxifying, nutrient-dense',
      emoji: '🥬',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&q=80',
    },
    // Lunch
    {
      name: 'Cucumber & Mint Raita Bowl',
      description: 'Cooling yogurt-based dish',
      calories: 280,
      protein: 16,
      carbs: 32,
      fats: 10,
      ingredients: ['Yogurt', 'Cucumber', 'Mint', 'Cumin', 'Rice'],
      benefits: 'Cooling, probiotic, aids digestion',
      emoji: '🥒',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80',
    },
    {
      name: 'Light Sushi Bowl',
      description: 'Deconstructed sushi with fresh fish',
      calories: 380,
      protein: 24,
      carbs: 52,
      fats: 8,
      ingredients: ['Sushi rice', 'Salmon', 'Avocado', 'Cucumber', 'Seaweed'],
      benefits: 'Light, refreshing, omega-3 rich',
      emoji: '🍣',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    },
    // Dinner
    {
      name: 'Grilled Chicken Salad',
      description: 'Light protein with fresh greens',
      calories: 360,
      protein: 38,
      carbs: 22,
      fats: 14,
      ingredients: ['Grilled chicken', 'Mixed greens', 'Cherry tomatoes', 'Cucumber', 'Vinaigrette'],
      benefits: 'High protein, light, refreshing',
      emoji: '🥗',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    },
    {
      name: 'Steamed Fish with Vegetables',
      description: 'Light steamed dinner',
      calories: 320,
      protein: 36,
      carbs: 24,
      fats: 10,
      ingredients: ['White fish', 'Broccoli', 'Carrots', 'Ginger', 'Soy sauce'],
      benefits: 'Light, easy to digest, high protein',
      emoji: '🐟',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1580959375944-1ab5b8c78f15?w=800&q=80',
    },
    // Snacks
    {
      name: 'Coconut Water & Fruit',
      description: 'Natural electrolyte drink',
      calories: 120,
      protein: 2,
      carbs: 28,
      fats: 1,
      ingredients: ['Coconut water', 'Fresh mango', 'Lime'],
      benefits: 'Hydrating, electrolytes, refreshing',
      emoji: '🥥',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1585238341710-4a1b0d2d1b5d?w=800&q=80',
    },
    {
      name: 'Chilled Buttermilk',
      description: 'Probiotic cooling drink',
      calories: 80,
      protein: 6,
      carbs: 10,
      fats: 2,
      ingredients: ['Buttermilk', 'Mint', 'Cumin', 'Salt'],
      benefits: 'Cooling, probiotic, aids digestion',
      emoji: '🥛',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80',
    },
  ],
  cloudy: [
    // Breakfast
    {
      name: 'Balanced Breakfast Plate',
      description: 'Eggs, toast, and vegetables',
      calories: 380,
      protein: 24,
      carbs: 36,
      fats: 16,
      ingredients: ['Eggs', 'Whole grain toast', 'Avocado', 'Tomatoes', 'Spinach'],
      benefits: 'Complete nutrition, balanced macros',
      emoji: '🍽️',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80',
    },
    {
      name: 'Multigrain Pancakes',
      description: 'Protein-rich pancakes with berries',
      calories: 360,
      protein: 18,
      carbs: 48,
      fats: 12,
      ingredients: ['Multigrain flour', 'Eggs', 'Berries', 'Honey', 'Greek yogurt'],
      benefits: 'High fiber, sustained energy',
      emoji: '🥞',
      mealType: 'breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&q=80',
    },
    // Lunch
    {
      name: 'Chicken Wrap',
      description: 'Grilled chicken with vegetables',
      calories: 420,
      protein: 32,
      carbs: 42,
      fats: 14,
      ingredients: ['Whole wheat wrap', 'Grilled chicken', 'Lettuce', 'Tomatoes', 'Hummus'],
      benefits: 'Balanced, portable, satisfying',
      emoji: '🌯',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
    },
    {
      name: 'Buddha Bowl',
      description: 'Balanced grain and veggie bowl',
      calories: 440,
      protein: 20,
      carbs: 58,
      fats: 16,
      ingredients: ['Quinoa', 'Chickpeas', 'Sweet potato', 'Kale', 'Tahini'],
      benefits: 'Complete nutrition, plant-based',
      emoji: '🥙',
      mealType: 'lunch',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    },
    // Dinner
    {
      name: 'Grilled Chicken with Rice',
      description: 'Classic balanced dinner',
      calories: 480,
      protein: 42,
      carbs: 52,
      fats: 12,
      ingredients: ['Grilled chicken', 'Brown rice', 'Broccoli', 'Carrots', 'Herbs'],
      benefits: 'High protein, balanced, filling',
      emoji: '🍗',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80',
    },
    {
      name: 'Pasta Primavera',
      description: 'Whole wheat pasta with vegetables',
      calories: 420,
      protein: 18,
      carbs: 64,
      fats: 12,
      ingredients: ['Whole wheat pasta', 'Mixed vegetables', 'Olive oil', 'Garlic', 'Parmesan'],
      benefits: 'Balanced, satisfying, veggie-rich',
      emoji: '🍝',
      mealType: 'dinner',
      imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    },
    // Snacks
    {
      name: 'Apple with Almond Butter',
      description: 'Classic healthy snack',
      calories: 180,
      protein: 6,
      carbs: 22,
      fats: 9,
      ingredients: ['Apple', 'Almond butter'],
      benefits: 'Fiber, healthy fats, satisfying',
      emoji: '🍎',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1568471173238-64ed8e7e9d8e?w=800&q=80',
    },
    {
      name: 'Trail Mix',
      description: 'Nuts, seeds, and dried fruit',
      calories: 160,
      protein: 6,
      carbs: 18,
      fats: 9,
      ingredients: ['Almonds', 'Walnuts', 'Dried cranberries', 'Pumpkin seeds'],
      benefits: 'Energy boost, healthy fats, portable',
      emoji: '🥜',
      mealType: 'snack',
      imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80',
    },
  ],
};

export const getWeatherBasedMealSuggestions = (
  weather: WeatherData,
  mealType?: MealType
): MealSuggestion[] => {
  const suggestions = weatherMeals[weather.category] || weatherMeals.cloudy;

  // Filter by meal type if specified
  if (mealType) {
    return suggestions.filter((meal) => meal.mealType === mealType);
  }

  return suggestions;
};
